### PR TITLE
Update futurama.json

### PR DESCRIPTION
**Pull request by bellingarc**
improved consistency of data fields in characters collection

### CODE REVIEW

**Comment by thedamian** [comment]
Hey @bellingarc 
Love any improvement. and I see the fix in the word "female" (thank you)
But:

1) any change to futurama.json should also be made to futurama.backup.json
2) Why move information into a sub category called "info" What do those fields meet to have them in "info" but not other fields? What were you trying to do?

**Comment by bellingarc** [comment]
Thank you for the advice regarding the first bullet point. Would that best be done in a second pull request? As for the second, I did not see any value in the "info" subcategory, and as the first several entries had no "info" subcategory, I removed it from the entries that did.

**Comment by jermbo** [comment]
Thanks for the update!

You can include the backup file in this pull request.

**Comment by thedamian** [comment]
@bellingarc I stand corrected on the #2 as I thought you were ADDING the info subcatetory and I was suggesting not having it. So your contribution would be amazing.

Put it all in this pull. simply copy and past it to the futurama.json.back upload it your repo and it'll be part of this pull request and like Jermbo said, we'll include it and you'll be FAMOUS :dizzy::dizzy::dizzy:

**Comment by bellingarc** [comment]
Thank you for the review and the advice, I believe I have updated the json backup and added it to this pull request.

**Comment by thedamian** [comment]
NUUUUUICE!

APPROVED!
:star_struck::star_struck::star_struck::star_struck::star_struck::star_struck:

**Pull request merged**
