### PR TITLE
Correct Beer rating

### PR DESCRIPTION
**Pull request by wesbos**
this was offensively low. Thanks for the cool API :)

### CODE REVIEW

**Comment by thedamian** [comment]
Why does this git pull request smell like comes from a little cottage with brand new walls. 
Thanks for finding this API Wes. Jermbo is very proud and there's a lot of us that have contributed. Glad you're another one that has done so.

**Comment by jermbo** [comment]
Thanks for the commit! Glad you've enjoyed the tool.

**Comment by wesbos** [comment]
Haha thanks a ton :D I'm going to use this in my next course if that is okay?

**Comment by jermbo** [comment]
I've been following your work for some time now and have all of your courses. It would be surreal to have my work featured in a course of yours! You can absolutely use this.

If there is a feature or endpoint you would like to see in here, please let me know.

**Comment by wesbos** [comment]
fantastic -thanks a lot!

**Pull request merged**
