### PR TITLE
Adding all simpsons episodes + All Characters (6000+)

### PR DESCRIPTION
**Pull request by thedamian**
Here you go jermbo. You owe me a colombian  🇨🇴  (not columbian) coffee! ☕  🔥

### CODE REVIEW

**Comment by thedamian** [comment]
Damian. You have to add the episodes into the existing simpson.json file not it's own file

**Comment by thedamian** [comment]
the correct label for the pr's is #hacktoberfest-accepted

**Comment by jermbo** [comment]
Where is the backup file?

**Comment by thedamian** [comment]
This should not be accepted as is as we have a simpson.json file and it should be merge and be an endpoint called "episodes"

**Comment by thedamian** [comment]
@jermbo corrected the mistake. Now the simpson-episodes.json is gone and it's part of the simpsons.json endpoint already in the system with the new sub-endpoint added to the apiList.json

**Comment by jermbo** [comment]
Looks good!

**Comment by thedamian** [comment]
Pushed all changes live at 12pm EST 10/08/2020

**Pull request merged**
