### PR TITLE
Main

### PR DESCRIPTION
**Pull request by jzacka1**
I created a new list for the SampleAPI.  It's a list of cartoons, both 2D and 3D, and I would like to  contribute to your project.

### CODE REVIEW

**Comment by thedamian** [comment]
Beautiful submittion.

Before being approved can you 

1) remove the .vs directory  :see_no_evil: (I've updated the .gitignore and added .vs, but you can do 'git rm .vs')
2) We won't see your contribution unless you add to the "src/apiList.js" file and add a new entry. My suggested change is below but please feel free to change it as you wish (probably the longDesc and desc should be changed by you.
`
  {
    id: 20,
    title: "Cartoons",
    longDesc:
      "If cartoons is what you like then boy do we have a full list of all the cartoons from the past and present and all their details including a amazingly sourced image to showcase",
    desc:
      "A list of Cartoons from your past.",
    link: "cartoons",
    graphLink: "cartoons/graphql",
    endPoints: [
      "2D",
      "3D",
    ],
    sampleCode: " \n fetch('https://sampleapis.com/cartoons/api/2D')\n .then(response => response.json())\n      .then(data =>  {\n        data.map(c => \n        {\n         console.log(c.title);\n        }\n      );\n  });"
  },
`

**Comment by jzacka1** [comment]
I'm trying to delete the sqllite file and merge the new changes into the current pull request, but I couldn't in Visual Studio.  I'm going to do some research on how to do it.

**Comment by jermbo** [comment]
Please add a backup file. Essentially, save `cartoons.json` as `cartoons.json.backup` and include this file. This is necessary to help restore everything if things get out of sync.

**Comment by thedamian** [comment]
@jzacka1 You're right. Here's what I suggest

1) in a new directory do a `https://github.com/jermbo/SampleAPIs.git`
2) copy your new added file to the direct directory: https://github.com/jzacka1/SampleAPIs/blob/main/src/api/cartoons.json
3) copy it again naming it cartoons.json.backup
4) edit the src/apiList.js file and add the entry with id 20 I suggested above (and make sure to change the desc and long_desc to something you like.
*5) add the `.vs' to the .gitignore file*
6) do a `git push --force` which will your changes and change your PR and your repo to not have the .vs files which are actual personal settings on your system.
6) WE ALL WIN!

**Pull request merged**
